import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
from main import answer_question

def test_answer_question_integration():
    """
    Integration test for answer_question(user_query) generated by gpt.
    Uses real embeddings, DB, and chat model.
    """

    # 1. Prepare a real user query
    query = "How do I reset my password?"

    # 2. Call the actual function without mocking anything
    result = answer_question(query) # using the function directly that makes this test as integration test

    # 3. Assertions
    assert result is not None  # function returns something
    assert len(result) > 0  # result is not empty
    assert isinstance(result, str)  # result should be a string
    assert "password" in result.lower()  # expected keyword in the response
